class Login():  
    email_textbox = '[name="identification"]'
    password_textbox = '[name="password"]'
    login_button = '[id ="ember11"]'
    my_account_button= '[class="gh-user-avatar relative"]'
    forgot_button= '[id="ember10"]'
    close_session_button= '[data-role=\'close_session_button\']'
    close_alert_button= '.header-desktop [data-role=\'close_alert_button\']'
    alert_pss = '[class="main-error"]'
    bton_site = '[class="relative"]:nth-child(2)'
    bton_dashboard = '[class="relative"]:nth-child(1)'
    bton_posts = '[id="ember26"]'
    bton_posts_new = '[class="ember-view gh-btn gh-btn-primary view-actions-top-row"]'
    posts_create = '[class="gh-editor-title ember-text-area gh-input ember-view"]'
    posts_create_body= '[class="koenig-editor__editor __mobiledoc-editor __has-no-content"]'
    bton_posts_add_item = '[aria-label="Add a card"]'
    bton_posts_add_item_mark = '[class="CodeMirror-scroll"]'
    btn_preview = '[class="gh-btn gh-editor-preview-trigger"]'
    btn_preview_movile = '[class="gh-post-preview-btn-group"] [class="gh-btn gh-btn-group-selected gh-post-preview-mode"]'
    btn_back = 'button[class="gh-editor-back-button"]'
    btn_list_publish ='[role="button"]'
    btn_publish = '[class="gh-btn gh-btn-black gh-publishmenu-button gh-btn-icon ember-view"]'
    btn_publish_modal = '[class="gh-btn gh-btn-black gh-btn-icon ember-view"]'
    btn_back_publish = '[class="ember-view gh-editor-back-button"]'
    cart_post1 = '//main[@id="site-main"]/div/div/article[2]/div/a'
    edit_page_btn = '[class="ember-view gh-btn gh-btn-outline mt2 mr2"]'
    movile_view = '[class="gh-btn gh-design-preview-mode gh-btn-group-selected"]'
    sd_brand= '[class="gh-nav-design-tab "] [class="gh-nav-button-expand"]'
    sd_description = '[id="site-description"]'
    sd_site_wide = 'div.gh-app nav.gh-nav.gh-nav-contextual section > div.gh-nav-top  button:nth-child(4)'
    save = '[class="gh-btn gh-btn-primary gh-btn-icon ember-view"]'
    settings = '[class="ember-view gh-nav-menu-back-button"]'

